set terminal pdf
set output "norec_gpu.pdf"
set xrange [0:32]
set yrange [0:150000000]
set y2range[0:150000000]
set ytics nomirror
set grid
set xlabel "Number of threads"
set ylabel " No. of Rectanges/Sec"
set title "GPU Thread Computation Cost"
set key right bottom
#set format y "10^{%L}"
#unset key
plot "noRec_gpu.dat" using 1:2 title "(600,600)"  axis x1y1  with lines lw 10 lt rgb "#006400",\
     "noRec_gpu.dat" using 1:3 title "(800,800)"  axis x1y1  with lines lw 10 lt rgb "blue"
